baseURL: https://www.dvontrecoleman.com 
title: Dvontre Coleman
defaultContentLanguage: 'en'
theme: eternity
googleAnalytics: '' # todo: set your analytics id.

params:
  image: /images/banner.png
  logo: logo.png # todo: add your custom logo to static/
  subtitle: Comedian, Writer, Black Man.
  copyright: All rights reserved. # todo: set your copyright type.
  author: Dvontre Coleman
  dontShowSource: false # please, do not do this :)
  dontShowLogo: true # If you want to hide the logo, this is what you set to true
  portfolio:
    columns:
      desktop:
        default: 3
      mobile:
        default: 2
  socials:
    # todo: add your social accounts.
    - icon: 'far fa-envelope fa-lg'
      url: 'mailto:eternity@bora.sh'
      landing: true
    # tik tok
    - icon: 'fa-brands fa-tiktok'
      url: 'https://www.tiktok.com/@dvontrecoleman'
      landing: true
  homepage: "/home" # todo: uncomment homepage, homepage link is mostly same with menu.main[0]
  specialPages:
    - work
    - archive
  bypassWelcomePage: false # redirects "/" to "homepage" when it's true.
  plausible: '' # todo: set your plausible id.
  disableWelcomePageBackground: false # disables the background image on the homepage
  disableRadius: false
  moveIt: false # Moves Title and Meta info down, only visible when scroll.
  disableAlwaysResize: false

# allows for use of html
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

permalinks:
  work: ":filename/"

# todo: uncomment menu.main array after you create contents.
menu:
  main:
  - name: home
    url: /home/
    weight: 1
  - name: mailing list
    url: /mailing_list/
    weight: 2
  - name: contact 
    url: /contact/
    weight: 3
