baseURL: https://www.dvontrecoleman.com 
title: Dvontre Coleman
defaultContentLanguage: 'en'
theme: eternity
googleAnalytics: '' # todo: set your analytics id.

params:
  image: /images/banner.png
  logo: logo.png # todo: add your custom logo to static/
  subtitle: Comedian, Writer, Black Man.
  copyright: All rights reserved. # todo: set your copyright type.
  author: Dvontre Coleman
  dontShowSource: false # please, do not do this :)
  dontShowLogo: true # If you want to hide the logo, this is what you set to true
  portfolio:
    columns:
      desktop:
        default: 3
      mobile:
        default: 2
  socials:
    # instagram
    - icon: 'fa-brands fa-instagram'
      url: 'https://www.instagram.com/dvontrecoleman/'
      landing: true
    # tik tok
    - icon: 'fa-brands fa-tiktok'
      url: 'https://www.tiktok.com/@dvontrecoleman'
      landing: true
    # twitter
    - icon: 'fa-brands fa-x-twitter'
      url: 'https://www.twitter.com/dvontre_coleman'
      landing: true
    # tik tok
    - icon: 'fa-solid fa-envelope'
      url: 'mailto:dvontrec+comedy@gmail.com'
      landing: true
  homepage: "/about"
  specialPages:
    - archive
  bypassWelcomePage: false # redirects "/" to "homepage" when it's true.
  plausible: '' # todo: set your plausible id.
  disableWelcomePageBackground: false # disables the background image on the homepage
  disableRadius: false
  moveIt: false # Moves Title and Meta info down, only visible when scroll.
  disableAlwaysResize: true

# allows for use of html
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

permalinks:
  work: ":filename/"

# todo: uncomment menu.main array after you create contents.
menu:
  main:
  - name: About
    url: /about/
    weight: 1
      #  - name: Media
      # url: /media/
      # weight: 2
  - name: Mailing List
    url: /mailing_list/
    weight: 3
  - name: Contact Me 
    url: /contact/
    weight: 4
